# num = "MISSISSIPPI" 
# i = 0
# a = 0
# b = 0
# c = 0
# d = 0
# LIST = []
# while i < len(num):
#     if num[i] == "M":
#        a = a + 1
#     if num[i] == "I":
#       b = b + 1 
#     if num[i] == "S":
#        c = c + 1
#     if num[i] == "P":
#        d = d + 1
#     i = i + 1
# M=("M",a,"I",b,"S",c,"P",d)
# print(M)

# num = "MISSISSIPPI"
# a = []
# x = {}
# for i in num:
#     a.append(i)
#     s = a.count(i)
#     x.update({i:s})
# print(x)
